### ISSUE TITLE
Disable formatting conversion

### ISSUE THREAD

**Issue by xPaw** [Syriiin/irc-to-discord#14]
The markdown->irc is quite buggy, and formats things it shouldn't (anything math, or anything with underscores breaks down).

I suggest just disabling it and sending it as-is, which is better than incorrectly formatted strings.

**Comment by Syriiin** [comment]
Yea that's probably a good idea until someone finds the time to implement a proper AST for discord parsing.
I've added this as a config option in 39d25cd9477cf34d25f3c0a8783677425d97fa60
