### ISSUE TITLE
Fix "Embed.Empty" and duplicate messages

### ISSUE THREAD

**Issue by xPaw** [Syriiin/irc-to-discord#15]
On IRC it looks like this:
```
22:24 <> <K​owiz> https://twitter.com/richgel999/status/1330767132003606528
22:24 <> <K​owiz> Embed.Empty: https://twitter.com/richgel999/status/1330767132003606528
```

1. Skip title if its empty (Embed.Empty)
2. Do not send embed the url was already contained in the actual message

**Comment by Syriiin** [comment]
Ah yea it seems discord sends automatic link embeds with the message payload now. (maybe this was always the case?)
Fixed in 1a12b54ade92f2f54a7f169a1b0ce74b7200e68b
