### ISSUE TITLE
Support discord replies

### ISSUE THREAD

**Issue by xPaw** [Syriiin/irc-to-discord#16]
I suggest just prepending the user the reply is to. I suspect this requires extra work if you are replying to a relayed message (so you need to regex out the original irc username?)

![image](https://user-images.githubusercontent.com/613331/103150496-70918080-477d-11eb-85d6-1380dc70bf37.png)

**Comment by Syriiin** [comment]
Yea, I'm just waiting on discord.py 1.6, which includes reply support in the library, to be released. Will push an update for this once it is released in the near future.

**Comment by Syriiin** [comment]
Added in 16485dd888ba135536f2a62483ad5a51d2d9d979
