### ISSUE TITLE
error on run

### ISSUE THREAD

**Issue by urbels** [Syriiin/irc-to-discord#2]
python irc-to-discord.py 
  File "irc-to-discord.py", line 33
SyntaxError: Non-ASCII character '\xe3' in file irc-to-discord.py on line 33, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by haxxus** [comment]
yep was gonna say the same , ummm

**Comment by haxxus** [comment]
print("Logged into discord as user: 「{}」".format(client.user.name))
I changed to 
print("Logged into discord as user: {}".format(client.user.name))

then error is on line 36 with return 

  File "irc-to-discord.py", line 36
    yield from client.change_presence(game=discord.Game(name=default_status))
             ^
SyntaxError: invalid syntax

**Comment by Syriiin** [comment]
Ah yes, I hadn't noticed this might be an issue on some systems, fixed in 0605dd85241a5c2c75a86fbe2cd511f3c2651d21
