### ISSUE TITLE
Feature request: user passthrough

### ISSUE THREAD

**Issue by SinZ163** [Syriiin/irc-to-discord#9]
Add a config option or even runtime configurable option to add discord or irc bridges to a whitelist where their message is either sent as is (and not prefixed with the bots name), or reparsed to use the name inside the message instead of the bot.

This can be an alternative option to #8 where an external service only needs to talk to irc OR discord, and the existing irc-to-discord bridge will make that service serve both protocols

**Comment by Syriiin** [comment]
Added in 1c01c976cf0badf05c9a2038084776b397fa8ff8
